test: improve scripts

diff --git a/tools/asan/bin/erl-asan b/tools/asan/bin/erl-asan
--- a/tools/asan/bin/erl-asan
+++ b/tools/asan/bin/erl-asan
@@ -1,4 +1,14 @@
 #!/bin/bash
+#
+
+die() {
+    echo "error: $1";
+    exit 1;
+}
 
 CERL=`command -v cerl`
+
+if [ -z "$CERL" ];then
+    die "cerl is missing, see https://www.erlang.org/doc/installation_guide/install"
+fi
 $CERL -asan "$@"
